### ISSUE TITLE
Non-destructive upgrade path

### ISSUE THREAD

**Issue by lmakarov** [dduportal/boot2docker-vagrant-box#16]
I'm trying to figure out a non-destructive upgrade path.

It is my understanding that when `dduportal/boot2docker` is updated with e.g. docker 1.6.0, the Vagrant VM has to be reinitialized (`vagrant destroy && vagrant up`), which will lead to loss of all images and containers stored on the persistent partition.

The following suggests that `vagrant reload` would be sufficient:
http://stackoverflow.com/questions/25914383/update-a-vagrant-box

Unfortunately when I do `vagrant up` with a previous box version:

```ruby
config.vm.box = "dduportal/boot2docker"
config.vm.box_version = "1.4.1"
```

then switch to the current version
```ruby
config.vm.box = "dduportal/boot2docker"
config.vm.box_version = "1.5.0"
```

and do `vagrant reload` I'm getting an ssh password prompt from the VM:

```
...
==> boot2docker: Booting VM...
==> boot2docker: Waiting for machine to boot. This may take a few minutes...
    boot2docker: SSH address: 127.0.0.1:2222
    boot2docker: SSH username: docker
    boot2docker: SSH auth method: private key
    boot2docker: Warning: Connection timeout. Retrying...
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
docker@127.0.0.1's password:
...
```

**Comment by tonivdv** [comment]
Hey @lmakarov ,

You do have this each time? What happens if you hit [enter] upon this message?

**Comment by lmakarov** [comment]
@tonivdv not each time, only when I switch from one version of the box to another. 
Hitting [enter] just bring another message like that regardless of the number of hits.

I assume the cause for the message is the SSH key mismatch.
Adding `config.ssh.insert_key = false` to my Vagrantfile indeed resolved the auth prompts.

However it looks like the box is stuck with the original docker/iso version unless you destroy and re-up it.

Below are the steps and results.

## Step 1 - starting with box v1.4.1

**Vagrantfile**
```ruby
...
config.vm.box = "dduportal/boot2docker"
config.vm.box_version = "1.4.1"
config.vm.box_check_update = false
config.ssh.insert_key = false
...
```

**Commands**
```bash
vagrant up
vagrant ssh
```

**Output**
```
Boot2Docker version 1.4.1, build master : 86f7ec8 - Tue Dec 16 23:11:29 UTC 2014
Docker version 1.4.1, build 5bc2ff8
```

## Step 2 - change the box version to 1.5.0 and reload

**Vagrantfile**
```ruby
config.vm.box = "dduportal/boot2docker"
config.vm.box_version = "1.5.0"
config.vm.box_check_update = false
config.ssh.insert_key = false
```

**Commands**
```bash
vagrant reload
vagrant ssh
```

**Output**
```
Boot2Docker version 1.4.1, build master : 86f7ec8 - Tue Dec 16 23:11:29 UTC 2014
Docker version 1.4.1, build 5bc2ff8
```

## Step 3 - `vagrant box update` and `vagrant reload`

```bash
vagrant box update
==> boot2docker: Checking for updates to 'dduportal/boot2docker'
    boot2docker: Latest installed version: 1.5.0
    boot2docker: Version constraints: 1.5.0
    boot2docker: Provider: virtualbox
==> boot2docker: Box 'dduportal/boot2docker' (v1.5.0) is running the latest version.
```

```bash
vagrant reload
vagrant ssh
```

```bash
Boot2Docker version 1.4.1, build master : 86f7ec8 - Tue Dec 16 23:11:29 UTC 2014
Docker version 1.4.1, build 5bc2ff8
```

## Step 4 - `vagrant destroy` and `vagrant up`

```bash
vagrant destroy
vagrant up
vagrant ssh
```

```
Boot2Docker version 1.5.0, build master : a66bce5 - Tue Feb 10 23:31:27 UTC 2015
Docker version 1.5.0, build a8a31ef
```

Further reading the Vagrant documentation (http://docs.vagrantup.com/v2/boxes/versioning.html):

>Vagrant can not and does not automatically download the updated box and update the machine because boxes can be relatively large and **updating the machine requires destroying it and recreating it**, which can cause important data to be lost. Therefore, this process is manual to the extent that the user has to manually enter a command to do it.

Which confirms my observations.

The only way I see the upgrade path possible is by sticking with the way boot2docker does things (e.i. boot from boot2docker.iso every time) and provide instructions on how to manually remount a new boot2docker.iso when a new one is released.

**Comment by tonivdv** [comment]
Thanks for this detailed explanation. Hope @dduportal can share his thoughts on this?

**Comment by dduportal** [comment]
Hi ! Thank you for all that stuff and thoughts ! Since i'm in a place with a poor internet access, i'll throw an eye.

After a quick read, i have 2 things in mind :
- the compatibility with vagrant 1.7.x came with my 1.5.0 box (see the changelog), it explains the SSH behaviour described .
- another recent change : instead of embeding the boot2docker iso, i've started to dump it on the first partition of the vm's harderive. I think dumping the new iso can be a first path to the upgrade without loosing your containers. But it won't solve the "vagrant settings" part which is at the box level. I'm starting to think about having a dedicated vm harddisk which is not stores inside the baseboxes. Another danger can be the docker's internal storage of images : if it change, you upgrade may destroy your content. The balance beetween energy for an upgrade feature and energy for solving this feature relatives bugs can be difficult.


I strongly recommend you to have an "ephemeral" container management process that can be rebuilt upon your SCMs, and accelerated thru local proxy and/or docker hubs (private or not), in order to avoid that difficult balance :)

**Comment by lmakarov** [comment]
>instead of embeding the boot2docker iso, i've started to dump it on the first partition of the vm's harderive.

What was the reasoning behind the workflow change around boot2docker.iso?

I was thinking about having a vagrant box that mounts the boot2docker.iso image from the host (the same way the stock boot2docker does this.) This way upgrading to a new docker/boot2docker version is as simple as replacing the iso with the new one and restarting the VM.

>dumping the new iso can be a first path to the upgrade without loosing your containers. 

What would be the actual steps to do this?

**Comment by lmakarov** [comment]
ping @dduportal ^^

**Comment by dduportal** [comment]
Hi, sorry, i was a lot busy those times.

The idea was to not posse the user with an iso, external to the VM's disk image which was a separate file, like in the original box from mitchellh.

I made that choice base on the fact that using vagrant make you aware about the create -> destroy workflow, which does not exists on native boot2docker.

I really think that you should use boot2docker and/or docker-machine if the case is to have a "durable" VM, because of the intrinsic ephemeral behaviour of vagrant's VMs (dev oriented). What is the added value, for your case, of using vagrant (and my box) ?

The idea, as I understand it, behind boot2docker is that you have a tool that manage docker for you, with long-living management.
The idea i see behind vagrant is reproducible and repeatable at VM level, which include provisioning, so you have to rebuild often.
That's why I don't see t he migration path need here : I see the dev-env as complete software part which should have its dependencies. So if you have to upgrade docker, as a dev dependency, you should rebuild your have at least at this moment, because you'll have time to do that, or delay the upgrade, the time for you to terminate what you are doing and not endangered your work.

Another important thing : the upgrade of my box follow Docker (and b2d) ones, but can also add some useful features which are outside the VM : port forwarding, implicit provisioning, etc. In that case, I fear that giving a migration path might be too complicated to maintain since changing vagrant's base box will change the root filesystem.

Maybe you should create different Vagrantfile (or use git SCM branches) for preparing /testing the upgrade ?
If you just want to upgrade the boot2docker, inside the box, just download the iso you want, and use the command that [boot2docker documentation states](https://github.com/boot2docker/boot2docker#install-on-any-device) : 
```
sudo dd if=/path/to/new/boot2docker.iso of=/dev/sda
```

but it seems risky.

If you have precise use case or advises, don't hesitate to describe it here, since I maybe don't foresee all :)

**Comment by lmakarov** [comment]
@dduportal 
>What is the added value, for your case, of using vagrant (and my box) ?

I'm working on a cross-platform docker based development environment. Your box is used as a base for my boot2docker-vagrant setup: https://github.com/blinkreaction/boot2docker-vagrant

Using a vagrant boot2docker box instead of the stock boot2docker/docker-machine has the following key benefits in my case:
 - synced folders options (nfs, smb, rsync)
 - network configuration
 - additional provisioning scripts
 - configuration in a YAML file (custom)

I've been thinking about getting rid of Vagrant as a dependency and implement all Vagrant features mentioned above manually with a bunch of scripts on top of the stock boot2docker/docker-machine.
However, the further the project goes, the less I'm sure this would be worth the hassle.

While I agree with you that development environments should be disposable and easily recyclable, I think that should be handled on the container level and not on the Docker Host level (vagrant VM).

Currently if I destroy and recreate the VM (the current update path), I'm losing all my project databases, since container volumes are stored on the Docker Host.  
While this is not critical and I can re-import databases from a backup, it is still a little annoying to do so for every project I have running using this environment.

>If you just want to upgrade the boot2docker, inside the box, just download the iso you want, and use the command that boot2docker documentation states ... but it seems risky.

What issues do you foresee with this approach?
This is basically the path the stock boot2docker is taking, right?

**Comment by dduportal** [comment]
Hello @lmakarov !

As for today, it seems that docker-machine and/or official boot2docker are better fit for your use case.

I still maintain this box, because it is useful in specific cases not addressed for today (corporate proxy, running homogeneously on vagrant providers). But keep in mind that the awesome work of recent months from Docker has lowered the diff.

But your problem will be mainly related by the use of Docker in your workflow : how to ensure all those things.

As I said, i consider that the development environments are part of your application, so it have to be rebuilt a lot.

You can manually copy the local data-volumes thru rsync and/or /vagrant mourned folder, but i don't want to provide any script for that.

If you think documentation can be updated with some example, do not hesitate to pull request, it'll be welcomed.

Thanks for providing you use cases.
