### ISSUE TITLE
Update to b2d 1.7.0

### ISSUE THREAD

**Issue by lmakarov** [dduportal/boot2docker-vagrant-box#23]
Just a place to collaborate :)

I noticed you already started working on the update, which is not trivial due to the b2d 1.7.0 changes (64bit userspace).

**Comment by dduportal** [comment]
Hello @lmakarov !

Good idea, i should write issues as "to do list" for next stuff, to improve visibility.
Anyway, the work you've seen on docker 1.7 is near-complete.

I found a way to replace syslinux (which is not provided as tcz package in 64 bits tiny core Linux, the OS boot2docker is based on) and ishybrid inside, by a manual compile of xorriso and reusing the .bin file images of the 32 bits tcz of syslinux (this image contains the hybrid MBR for bootable images, which is not bound to arch, as difference than the isohybrid binary).

It build fine, boot fine, and my quick tests where fine.

I'm focusing on the non regression tests on NFS and rstnc synced folder, since people seems to use my box for that functionality instead if using machine :)

Do not hesitate to build yourself and confirm its working on you configuration !

**Comment by lmakarov** [comment]
@dduportal take a look at this https://github.com/boot2docker/boot2docker/issues/936

There's no rsync for TinyCore 64bit...
The one you are pulling is 32bit and won't work - failed test `not ok 14 We can share folder thru rsync`

So far the most reasonable approach is to just stick in a compiled binary manually, like https://github.com/boot2docker/boot2docker/issues/936#issuecomment-114675231 suggests.

**Comment by dduportal** [comment]
@lmakarov, this is exactly what i had in mind. I've successfully tested it in a private boot2docker box for my company yesterday and it works fine.

I'll plan a release tomorow, i'll push some code today to let you review.

Thank you for your help !

**Comment by dduportal** [comment]
Hop, PR if you want to play with, I have not tested the rsync part, but it build with Windows : https://github.com/mitchellh/boot2docker-vagrant-box/pull/84

**Comment by dduportal** [comment]
Released on Atlas : https://atlas.hashicorp.com/dduportal/boxes/boot2docker/versions/1.7.0
