### ISSUE TITLE
private_network collision

### ISSUE THREAD

**Issue by chris-redekop** [dduportal/boot2docker-vagrant-box#31]
The static 192.168.10.1 private_network defined in the box's Vagrantfile at

https://github.com/dduportal/boot2docker-vagrant-box/blob/d9cbb2b092fb2cd1dfab891c9c6c3f1c8ac02a78/vagrantfile.tpl#L23

can collide with the host machine's local network.

I don't think this network configuration can be overridden by a project-level Vagrantfile.  (According to [its documentation](https://docs.vagrantup.com/v2/vagrantfile/index.html), Vagrant does not override network configuration.)

Might it be better, then, to leave this private_network configuration out of boot2docker-vagrant-box?

**Comment by dduportal** [comment]
Hello @chris-redekop !

Thanks for reporting.

This can, indeed, lead to problems. We wanted to provide an Out-Of-the-Box solution, given that we have a lot of Mac user interested in this box.

The solution your provide seems good : adding a bit of documentation. But since I really want to provide default support of NFS shared folder, private_network is mandatory.

I propose this one : we can do a "batteries included but removable" idea : as for NFS, we can implement an env VAR that can, at least, disable the private network (and another one to configure the IP), what do you think ?

**Comment by chris-redekop** [comment]
That sounds great.

I was secretly hoping Vagrant supported disabling the network; but, barring that, box-level support for disabling the network is a fine sol'n.

Thanks!

**Comment by dduportal** [comment]
Hello @chris-redekop : I just implemented this behaviour in https://github.com/dduportal/boot2docker-vagrant-box/pull/39.

**Comment by dduportal** [comment]
Box released under atlas : https://atlas.hashicorp.com/dduportal/boxes/boot2docker/versions/1.8.2

Feel free to re-open the issue if it does not fit to your needs :)
