### ISSUE TITLE
Upgrading a Vagrant box based on this image

### ISSUE THREAD

**Issue by inkel** [dduportal/boot2docker-vagrant-box#32]
First of all, thank you for your efforts. This is awesome work!

recently upgraded my local Docker installation to `1.8.0`. I had a custom Vagrant box running from the following `Dockerfile`: 

```Dockerfile
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|
  config.vm.box = "dduportal/boot2docker"
  config.vm.network "private_network", ip: "192.168.32.64"
end
```

After I've upgraded Docker, when I tried to list my images I've got the following error:

```
$ docker images
Error response from daemon: client and server don't have same version (client API version: 1.20, server API version: 1.19)
```

This box already has several custom images I've built, and I'd rather not rebuild them. How can I upgrade my Vagrant box?

Thanks.

**Comment by dduportal** [comment]
Hello !

I just released the 1.8.1 basebox : https://atlas.hashicorp.com/dduportal/boxes/boot2docker/versions/1.8.1

In your case I see 4 roads :
* Download the docker 1.7.1 binary to use with the basebox instead of the 1.8.x one OR use the client which is inside the VM, since it has the same version than the embedded engine
* Manually upgrade your boot2docker install : dump the stock boot2docker.iso 1.8.1 to the first partition of the VM hard drive : quite risky but works
* Save your images as tar files on the /vagrant share, destroy and upgrade the box, reimport them (no rebuild => such quick :) )
* Improve your development process to not suffer docker upgrade like this since there is one per month
