### ISSUE TITLE
Custom package installation need to be updated

### ISSUE THREAD

**Issue by AlbanMontaigu** [dduportal/boot2docker-vagrant-box#41]
Hello,

Sorry my fork is too divergent now to do a simple pull request so I open this issue.

In **scripts/build-custom-iso.sh**

You have 

```
curl -LO "http://tinycorelinux.net/5.x/x86/tcz/${TCZ_PACKAGE}.tcz";
````

**This legacy code leads to 2 issues today :**
* Now tiny core version is 6.4.1 so 5.x packages are outdated
* Now boot2docker arch is x86_64 so packages installed with this legacy code won't work and commands usage will result to "not found commands"

**I propose this fix :**
```
curl -LO "http://tinycorelinux.net/$(version | cut -d '.' -f 1).x/x86_64/tcz/${TCZ_PACKAGE}.tcz";
```

This should work and probably allow to avoid (don't know the goal of that) the custom install of rsync later in the script.

Kind regards.

**Comment by AlbanMontaigu** [comment]
Ok I confirm, custom rsync is no more requested, with the previous fix I propose you cand do the install like this : 
```
for TCZ_PACKAGE in popt attr acl rsync; do
```
Don't forget attr and acl, that are required for rsync

With this rsync will come in version 3.1.1.

**Comment by dduportal** [comment]
Hey, thank you for pointing that !

The legacy reason was to build a custom rsync that would have been > 3.x (vagrant constraint), since the old 5.x package of tinycore where only handling 2.x version. 

Your solution is working well !
BUT (alaways a but ;) ) :

As you point out, the default rsync package is now ok.
Vagrant as also been updated to handle that ([See this commit](https://github.com/mitchellh/vagrant/commit/26fe5ac89f4499e024f6ab12d87f97d61b212a86)) when boot2docker was updated to 64 bits (and tcl 6) with the 1.7.x release, month ago, i missed that :)

So : hardcore fix, I just removed the whole script since we do not need it anymore (see this commit) while upgrading to docker 1.9.1 - https://github.com/dduportal/boot2docker-vagrant-box/commit/a8b64fb9fcdc5c74c43c29a68a57b79cf6876b9b 

Thanks a lot, the 1.9.1 box is in the build, if the Belgian energy network is with me today !

**Comment by dduportal** [comment]
Here is a full comparison beetween 1.9.0 and 1.9.1 : https://github.com/dduportal/boot2docker-vagrant-box/compare/dduportal:dduportal-1.9.0...dduportal-1.9.1

**Comment by AlbanMontaigu** [comment]
Thanks as usual, you dig a little bit more :D 

But 1 question, as you removed build custom iso, how new commands can be integrated in b2d ? I mean directly inside not with live provisioning with something like bootlocal.sh.

Build custom iso is no more requested to do thant ? For example to integrate make or some other tools people may want.

Regards.

**Comment by dduportal** [comment]
You are completely right : It is not possible, "as it".
The bootlocal.sh is the solution if you have a "short term" need that i'm not quick enough to integrate here.

But you're right :
* docker-toolbox, with Machine, are ways better than my box with vagrant in a lot of use cases.
* Docker user are starting to master the "do it inside a container" which tend to lower the request (example for make : wheter do it in Windows or inside a container). 

But if anyone has a need and want to use my box, just opne an issue, it would be a pleasure to try to revert the "custom" build script.

=> Another important is that boot2docker should move to debian in the future, so it will be easier to tune (so i'll be providing less value here :) )

**Comment by AlbanMontaigu** [comment]
Thanks,

Your totally right luke, my question was for confirmation.

However, I will keep your old tip for iso customisation, because I'll stay in the obscur side a little bit more :)

May the force be with you.

**Comment by dduportal** [comment]
![Palpatine](http://www.quickmeme.com/img/e1/e1d999d47703d373612ad6b4e98b755fe5bf1303f5f3d7b3133384c5a142444d.jpg) 

;)

**Comment by AlbanMontaigu** [comment]
looool +1
