### ISSUE TITLE
Vagrant does not wait long enough for the Docker service to start

### ISSUE THREAD

**Issue by p120ph37** [dduportal/boot2docker-vagrant-box#45]
When bringing a vm online, Vagrant pauses to wait for the ssh service to start, then continues.
In the case of provider-docker, the next step (provisioning a Docker container inside the VM) requires the Docker service be running.
With your boot2docker image, this is not immediately true...
In `/opt/bootscript.sh`, the SSH daemon is initialized a while before the Docker daemon, leaving room for a race condition.
I was able to solve this by moving the SSH initialization after the Docker startup.

Here is the sed script I am currently using for this:

```
# make sure Docker starts before SSH
sed -i \
 -e '/Launch Docker/,$!{/Configure SSHD/,/^$/{H;d;};}' \
 -e '/Launch Docker/,/^$/{/^$/g;}' \
 /opt/bootscript.sh
```

(This is my current full work-around config: https://gist.github.com/p120ph37/0e2dc718c9ea3400da0590792eac208f )

**Comment by dduportal** [comment]
This is an interesting problem here. The services loading order is the default boot2docker one: it is required by boot2docker, in the context of a portable and repeatable executions.
This is required for example by docker-machine, to let the Docker daemon being configured from outside, before starting.

I understand the problem in your case, but I'm thinking that the "Docker provider" of Vagrant does not bring a lot of values, compared to storing a docker-compose file and use a shell provisioner to docker-compose up. This is a conceptual problem: wether you want to fit in vagrant idioms & paradigm, and you just cannot using boot2docker (due to those race conditions). Moving to a tiny debian/Arch image may helps, wether you want to go Docker, and should considers uncoupling Vagrant and Docker stack by using a shell script that will launch the docker stacks (compose is a good workflow engine-like tool here).

Maybe it can helps you, by using the embedded provisioning provided by my image: you can place a `bootlocal.sh`script next to your Vagrantfile. This will be executed in the boot2docker boot sequence, after ssh and docker start.

Thanks for taking time !

**Comment by dduportal** [comment]
BtW I'm closing the issue, feel free to reopen if you want to discuss :)
