### ISSUE TITLE
When and how is the docker daemon started?

### ISSUE THREAD

**Issue by Vad1mo** [dduportal/boot2docker-vagrant-box#8]
I used @YungSang boot2docker and it seems there are differences in when docker daemons is started.

I have two goals:
1. set EXTRA_ARGS in  /var/lib/boot2docker/profile
2. login into docker hub.
 
in @YungSang box 1.) is ignored because docker is already running at that time.
in @dduportal box 2.) is not possible because docker daemon is not running yet.

So the question is how could I resolve this problem with your box, when and how is the daemon started?

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

unless Vagrant.has_plugin?("nugrant")
  raise Vagrant::Errors::VagrantError.new, "Please install the nugrant plugin running 'vagrant plugin install nugrant'"
end
# Enviromentn definition
TARGET_ENV = "dev"
DOMAIN_PREFIX = "#{TARGET_ENV}"

Vagrant.require_version ">= 1.7.1"
Vagrant.configure(2) do |config|
  config.vm.define "#{TARGET_ENV}_env"
  config.vm.box = "dduportal/boot2docker"
  
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = 1024
  end

  config.vm.network "public_network"
  
  config.vm.synced_folder "~", "/vagrant_data"

  DNS_ADDR = "172.17.42.1"
  #Set DNS for dockerDNS container
  config.vm.provision :shell, inline: "echo EXTRA_ARGS=\\\"--bip=#{DNS_ADDR}/16 --dns=#{DNS_ADDR}\\\" > /var/lib/boot2docker/profile"

  config.vm.provision :shell, inline: "/etc/init.d/docker status"   
  #
  config.vm.provision :shell do |s|
    s.inline = "/usr/local/bin/docker $@"
    s.args   = ["login", "-u", config.user.docker.username, "-p", config.user.docker.password, "-e", config.user.docker.email]
  end
```

**Comment by dduportal** [comment]
Hi @Vad1mo !
First of all is "How does boot2docker start the Docker daemon" (e.g. the vanilla b2d, not the vagrant boxes we are talking about). :
* That script is run when b2d boot : https://github.com/boot2docker/boot2docker/blob/master/rootfs/rootfs/bootscript.sh. After mounting cgroups/FS/etc., it will :
  * run /etc/rc.d/docker - https://github.com/boot2docker/boot2docker/blob/master/rootfs/rootfs/etc/rc.d/docker - who'is going to do the /etc/init.d/docker start
  * If /var/lib/boot2docker/bootsync.sh and/or /var/lib/boot2docker/bootlocal.sh are found, it will run them

=> So this is asyncronous :
* Vagrant launch b2d and try to connect in SSH, while b2D init it boot sequence
* sshd has been launched before Docker byy bootscript.sh : vagrant start its config (plugin, mount /vagrant, provisionning) while docker daemon try to start

So if you want to write something inside /var/lib/boot2docker/profile, you have to launch a ```sudo /etc/init.d/docker restart``` just after, whatever box and config you use, in order to tell the Daemon to apply those new settings.
Note that, once written in the file, you don't have to rewritte and/or restart the daemon : each time you'll reboot the box, it will be taken in account.

For your provisionning, you can :
* Use the file provisionner to copy a "profile" file inside the VM, overwritting the existing one, and use a inline shell provisionner to do a sudo /etc/init.d/docker restart
* Use a full script provisionner which will take care to :
  * Stop docker daemon
  * Write (be carefull to be idempotent !) the profile
  * Start the Docker daemon.


If neither works, could you please provide me the resulting Vagrantfile + script, but also logs :
* From vagrant up command
* From inside the VM (/var/lib/boot2docker/docker.log)

**Comment by dduportal** [comment]
Just for complemental information, if you have a bootlocal.sh script next to your Vagrantfile, it will be run at each boot, after docker, ssh and /vagrant share are ok, but asynchronously of vagrant.
